# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-31 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161231_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={},
        ),
    ]
